import json
import logging
from pathlib import Path

import geopandas as gpd
import pytest
from shapely.geometry import Polygon

from data_pipeline.processing.geo import process_boundaries


def _write_test_shapefile(tmp_path: Path, records: list[dict]) -> Path:
    shapefile_dir = tmp_path / "source"
    shapefile_dir.mkdir(parents=True, exist_ok=True)
    shapefile_path = shapefile_dir / "D_lowPopMap_A.shp"
    gdf = gpd.GeoDataFrame(records, crs="EPSG:4326").to_crs(epsg=3857)
    gdf.to_file(shapefile_path)
    return shapefile_path


def test_process_ssc_boundaries_generates_geojson_and_manifest(tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
    shapefile_path = _write_test_shapefile(
        tmp_path,
        [
            {
                "SSC_CODE": "101",
                "SSC_NAME": "ALPHA HILL",
                "LGA_NAME": "BRISBANE INNER",
                "STATE": "qld",
                "AREA_SQKM": 10.5,
                "geometry": Polygon([(153.00, -27.00), (153.05, -27.00), (153.05, -26.95), (153.00, -26.95)]),
            },
            {
                "SSC_CODE": "102",
                "SSC_NAME": "BETA CREEK",
                "LGA_NAME": "BRISBANE INNER",
                "STATE": "qld",
                "AREA_SQKM": 12.25,
                "geometry": Polygon([(153.06, -27.00), (153.11, -27.00), (153.11, -26.95), (153.06, -26.95)]),
            },
            {
                "SSC_CODE": "201",
                "SSC_NAME": "GAMMA FLATS",
                "LGA_NAME": "DARLING DOWNS",
                "STATE": "qld",
                "AREA_SQKM": 8.75,
                "geometry": Polygon([(151.90, -28.10), (151.96, -28.10), (151.96, -28.04), (151.90, -28.04)]),
            },
        ],
    )
    boundaries_dir = tmp_path / "frontend" / "assets" / "geo" / "boundaries"
    manifest_path = tmp_path / "frontend" / "src" / "services" / "boundaries" / "sscManifest.ts"
    legacy_suburbs_dir = boundaries_dir / "suburbs"
    legacy_suburbs_dir.mkdir(parents=True, exist_ok=True)
    (legacy_suburbs_dir / "legacy.json").write_text("{}", encoding="utf-8")
    (boundaries_dir / "lga_boundaries.json").write_text("{}", encoding="utf-8")

    with caplog.at_level(logging.INFO, logger=process_boundaries.LOGGER.name):
        stats = process_boundaries.process_ssc_boundaries(
            shapefile_path=shapefile_path,
            out_dir=boundaries_dir,
            manifest_path=manifest_path,
        )

    assert stats["feature_count"] == 3
    assert stats["group_count"] == 2
    # Legacy assets are intentionally preserved until Story 1.2 switches BoundaryStore
    assert (boundaries_dir / "lga_boundaries.json").exists()
    assert legacy_suburbs_dir.exists()

    coarse_path = boundaries_dir / "ssc_coarse.json"
    detail_dir = boundaries_dir / "ssc"
    assert coarse_path.exists()
    assert detail_dir.exists()
    assert "\n" not in coarse_path.read_text(encoding="utf-8")

    coarse_collection = json.loads(coarse_path.read_text(encoding="utf-8"))
    assert coarse_collection["type"] == "FeatureCollection"
    assert {feature["properties"]["group_id"] for feature in coarse_collection["features"]} == {
        "group_brisbane_inner",
        "group_darling_downs",
    }

    brisbane_detail = json.loads((detail_dir / "group_brisbane_inner.json").read_text(encoding="utf-8"))
    assert brisbane_detail["type"] == "FeatureCollection"
    assert [feature["id"] for feature in brisbane_detail["features"]] == ["ssc_101", "ssc_102"]
    first_feature = brisbane_detail["features"][0]
    assert first_feature["properties"] == {
        "id": "ssc_101",
        "name": "Alpha Hill",
        "state": "QLD",
        "group_id": "group_brisbane_inner",
        "area_sqkm": pytest.approx(10.5),
    }
    assert first_feature["geometry"]["type"] == "Polygon"

    manifest_text = manifest_path.read_text(encoding="utf-8")
    assert manifest_text.startswith("// Auto-generated by process_boundaries.py - DO NOT EDIT\n")
    assert 'import { FeatureCollection } from "geojson";' in manifest_text
    assert 'export const sscCollections: Record<string, FeatureCollection> = {' in manifest_text
    assert (
        '"group_brisbane_inner": require("../../../assets/geo/boundaries/ssc/group_brisbane_inner.json"),'
        in manifest_text
    )
    assert (
        '"group_darling_downs": require("../../../assets/geo/boundaries/ssc/group_darling_downs.json"),'
        in manifest_text
    )

    assert any("Shapefile columns:" in message and "LGA_NAME" in message for message in caplog.messages)
    assert any("Processing completed in" in message for message in caplog.messages)
    assert any("Output file" in message for message in caplog.messages)


def test_process_ssc_boundaries_rejects_missing_required_columns(tmp_path: Path) -> None:
    shapefile_path = _write_test_shapefile(
        tmp_path,
        [
            {
                "SSC_CODE": "101",
                "LGA_NAME": "BRISBANE INNER",
                "STATE": "QLD",
                "geometry": Polygon([(153.00, -27.00), (153.05, -27.00), (153.05, -26.95), (153.00, -26.95)]),
            }
        ],
    )

    with pytest.raises(ValueError, match="SSC name"):
        process_boundaries.process_ssc_boundaries(
            shapefile_path=shapefile_path,
            out_dir=tmp_path / "assets" / "geo" / "boundaries",
            manifest_path=tmp_path / "src" / "services" / "boundaries" / "sscManifest.ts",
        )


def test_load_shapefile_raises_for_missing_input(tmp_path: Path) -> None:
    missing_path = tmp_path / "missing" / "D_lowPopMap_A.shp"

    with pytest.raises(FileNotFoundError, match="Shapefile not found"):
        process_boundaries.load_shapefile(missing_path)


def test_area_sqkm_computed_from_geometry_when_no_area_column(tmp_path: Path) -> None:
    """When shapefile has no area column, area_sqkm should be computed from geometry."""
    shapefile_path = _write_test_shapefile(
        tmp_path,
        [
            {
                "SSC_CODE": "101",
                "SSC_NAME": "ALPHA HILL",
                "LGA_NAME": "BRISBANE INNER",
                "geometry": Polygon([(153.00, -27.00), (153.05, -27.00), (153.05, -26.95), (153.00, -26.95)]),
            },
        ],
    )
    boundaries_dir = tmp_path / "frontend" / "assets" / "geo" / "boundaries"
    manifest_path = tmp_path / "frontend" / "src" / "services" / "boundaries" / "sscManifest.ts"

    process_boundaries.process_ssc_boundaries(
        shapefile_path=shapefile_path,
        out_dir=boundaries_dir,
        manifest_path=manifest_path,
    )

    detail_file = boundaries_dir / "ssc" / "group_brisbane_inner.json"
    detail = json.loads(detail_file.read_text(encoding="utf-8"))
    area = detail["features"][0]["properties"]["area_sqkm"]
    assert area is not None
    assert area > 0


def test_parse_args_defaults_and_overrides() -> None:
    """CLI argument parsing with defaults and overrides."""
    defaults = process_boundaries.parse_args([])
    assert defaults.shapefile == process_boundaries.SSC_SHP
    assert defaults.group_field is None
    assert defaults.simplify_tolerance == process_boundaries.SIMPLIFY_TOLERANCE

    custom = process_boundaries.parse_args([
        "--shapefile", "/tmp/test.shp",
        "--group-field", "SA3_NAME",
        "--simplify-tolerance", "0.001",
    ])
    assert custom.shapefile == Path("/tmp/test.shp")
    assert custom.group_field == "SA3_NAME"
    assert custom.simplify_tolerance == 0.001


def test_custom_simplify_tolerance_affects_output(tmp_path: Path) -> None:
    """Higher tolerance should produce simpler geometry (fewer coordinates)."""
    records = [
        {
            "SSC_CODE": "101",
            "SSC_NAME": "ALPHA HILL",
            "LGA_NAME": "BRISBANE",
            "geometry": Polygon([
                (153.00, -27.00), (153.01, -27.005), (153.02, -27.001),
                (153.03, -27.006), (153.04, -27.002), (153.05, -27.00),
                (153.05, -26.95), (153.00, -26.95),
            ]),
        },
    ]

    results = {}
    for label, tolerance in [("fine", 0.0001), ("coarse", 0.01)]:
        run_dir = tmp_path / label
        shapefile_path = _write_test_shapefile(run_dir, records)
        boundaries_dir = run_dir / "out"
        manifest_path = run_dir / "manifest" / "sscManifest.ts"
        process_boundaries.process_ssc_boundaries(
            shapefile_path=shapefile_path,
            out_dir=boundaries_dir,
            manifest_path=manifest_path,
            simplify_tolerance=tolerance,
        )
        coarse = json.loads((boundaries_dir / "ssc_coarse.json").read_text(encoding="utf-8"))
        results[label] = len(json.dumps(coarse))

    assert results["coarse"] <= results["fine"]


def test_resolve_field_mapping_rejects_invalid_group_field() -> None:
    """Requesting a non-existent group field should raise ValueError."""
    columns = ["SSC_CODE", "SSC_NAME", "geometry"]
    with pytest.raises(ValueError, match="was not found"):
        process_boundaries.resolve_field_mapping(columns, group_field="NONEXISTENT")
